@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar

POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{"test" : "post test",
"make": "sillymake",
"model":"sillymodel"
}

###
@newCar = {{postACar.response.body._id}}


###
GET  {{endpoint}} HTTP/3.0
content-type: application/json

###
GET http://localhost:3000/api/v1/cars HTTP/1.1
content-type: application/json
x-api-key: blahblah


###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json


###
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/6ab542a7892e15d4ed67bcff HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

{ "test" : "post test"
}