@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar

POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{"test" : "post test",
"make": "sillymake",
"model":"sillymodel",
"year": 2020
}

###
@newCar = {{postACar.response.body._id}}


###
GET  {{endpoint}} HTTP/3.0
content-type: application/json
x-api-key: blahblah

###
GET http://localhost:3000/api/v1/cars HTTP/1.1
content-type: application/json
x-api-key: blahblah


###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json
x-api-key: blahblah


###
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/6ab542a7892e15d4ed67bcff HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/6abcd184b66431348f09dd58 HTTP/3.0
content-type: application/json
x-api-key: blahblah

{ "make": "sneed",
  "model": "chuck",
  "year": 2021
}